[deps]
DistributionTestCases = "ee9588fa-d3ac-11e9-2cb3-b3040bb0eda3"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"

[compat]
DistributionTestCases = "0.2"
PowerModels = "0.13"
PowerModelsDistribution = "0.6"
